// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;


public class MenuCommand_AssetRefResourcePathRepair
{
	[MenuItem("Assets/AssetRef ResourcePath Repair")]
	public static void MenuCommand_Domain()
	{
		foreach(var rObject in Selection.objects)
		{
			if (rObject is GameObject)
			{
				foreach(var rComponent in (rObject as GameObject).GetComponentsInChildren<MonoBehaviour>(true))
					AssetRefExpand.EnumFieldAndInvoke(rComponent, -1, "ResourcePathRepair");
			}
			else
			{
				AssetRefExpand.EnumFieldAndInvoke(rObject, -1, "ResourcePathRepair");
			}
		}
	}
}

